name: Run Datadog Synthetic tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: environment_variables

    steps:
    - uses: actions/checkout@v4

    - name: Run Datadog Synthetic tests
      uses: DataDog/synthetics-ci-github-action@d51a08dcfc6a98c45d66ae188c47e46010271be0
      with:
        api_key: ${{secrets.DD_API_KEY}}
        app_key: ${{secrets.DD_APP_KEY}}
        test_search_query: 'tag:e2e-tests'


